import { ErrorBanner } from "@/components/ErrorBanner";
import { UseCaseCard } from "@/components/UseCaseCard";
import { serverApi } from "@/lib/server-api";

export default async function UseCasesPage() {
  const useCases = await serverApi.getUseCases();

  return (
    <>
      <header className="border-b border-line bg-card px-8 py-7">
        <h1 className="text-[28px] font-bold leading-tight tracking-[-0.01em] text-ink">
          Supported Use Cases
        </h1>
        <p className="mt-1.5 text-[15px] text-ink-muted">
          The four audit requirements this POC supports, with their mandatory
          inputs and required evidence.
        </p>
      </header>

      <div className="mx-auto max-w-detail px-8 py-8">
        {useCases === null ? (
          <ErrorBanner
            title="Backend not reachable"
            message="Start the API with: uvicorn app.main:app --port 8000"
            tone="warning"
          />
        ) : (
          <>
            <p className="text-[13px] text-ink-muted">
              Required evidence is loaded from the Requirement Catalog
              configuration, never generated by the language model.
            </p>
            <div className="mt-5 grid gap-5 lg:grid-cols-2">
              {useCases.map((useCase) => (
                <UseCaseCard
                  key={useCase.use_case_id}
                  useCase={useCase}
                  showEvidence
                />
              ))}
            </div>
          </>
        )}
      </div>
    </>
  );
}
