"""LangSmith sink: turns normalized spans into a LangSmith run hierarchy using the current SDK primitives.

* Workflow / agent / tool spans use `langsmith.trace(...)` (the SDK's context-manager API). Entering it sets the
  SDK's ambient run-tree context, so LangChain / LangGraph calls made inside a span are traced natively by
  LangChain's own tracer *as children of that span* (no duplicate instrumentation, readable nesting).
* Root spans are wrapped in `langsmith.tracing_context(enabled=True, client=..., project_name=...)`, so tracing is
  driven by this module's configuration rather than by process-global environment variables.
* LLM spans are created after the fact (`RunTree.create_child(...).post()`), and only when the call was NOT
  already traced natively by LangChain. That avoids two LLM runs for one model call while still giving
  non-LangChain providers a proper `llm` run with token usage.
* Point events (retry, fallback, validation, correlation) become run events + filterable metadata on the
  innermost open run.
* One shared `Client` per sink; the SDK batches and sends in a background thread, so nothing here blocks on the
  network. The client's `hide_inputs` / `hide_outputs` hooks apply the capture policy and the redactor to every run
  it sends — including runs generated by LangChain/LangGraph.
"""
import logging
from contextlib import ExitStack
from dataclasses import dataclass
from typing import Any

from observability.context import Span
from observability.enums import SPAN_EVENTS, EventType, RunType, Status
from observability.exceptions import SinkError
from observability.interfaces import ObservabilitySink
from observability.models import ObservabilityEvent
from observability.redaction import Redactor
from observability.serializers import to_jsonable
from observability.utils import enum_value, iso_utc

log = logging.getLogger("observability")

_LS_RUN_TYPES = {RunType.WORKFLOW: "chain", RunType.AGENT: "chain", RunType.LLM: "llm", RunType.TOOL: "tool"}
_STATE_KEY = "langsmith"
# span lifecycle event values (plain strings: str-Enum members hash by name, so never mix them in sets)
_LIFECYCLE = frozenset(e.value for group in SPAN_EVENTS.values() for e in group)
# event fields worth copying onto LangSmith run events / metadata
_EVENT_FIELDS = ("reason", "outcome", "retry_number", "retry_count", "previous_error_type",
                 "error_type", "error_message", "linked_trace_id", "request_id", "component", "operation", "status")


_USAGE_META_KEYS = ("model_name", "model", "token_usage", "finish_reason", "system_fingerprint")


def _usage_skeleton(outputs: Any) -> dict[str, Any]:
    """Content-free copy of an LLM run's outputs that keeps only what LangSmith needs for token/model stats."""
    if not isinstance(outputs, dict):
        return {}
    out: dict[str, Any] = {}
    gens = outputs.get("generations")
    if isinstance(gens, list):
        skeleton = []
        for batch in gens:
            row = []
            for g in batch if isinstance(batch, list) else [batch]:
                msg = g.get("message") if isinstance(g, dict) else None
                kw = msg.get("kwargs", {}) if isinstance(msg, dict) else {}
                if not isinstance(kw, dict):
                    kw = {}
                meta = kw.get("response_metadata") if isinstance(kw.get("response_metadata"), dict) else {}
                new_kw = {"type": kw.get("type", "ai"), "content": "",
                          "response_metadata": {k: meta[k] for k in _USAGE_META_KEYS if k in meta}}
                if kw.get("usage_metadata") is not None:
                    new_kw["usage_metadata"] = kw["usage_metadata"]
                row.append({"type": g.get("type") if isinstance(g, dict) else None, "text": "",
                            "message": {**{k: msg[k] for k in ("lc", "type", "id") if isinstance(msg, dict) and k in msg},
                                        "kwargs": new_kw}})
            skeleton.append(row)
        out["generations"] = skeleton
    llm_output = outputs.get("llm_output")
    if isinstance(llm_output, dict):
        out["llm_output"] = {k: llm_output[k] for k in _USAGE_META_KEYS if k in llm_output}
    if outputs.get("usage_metadata") is not None:
        out["usage_metadata"] = outputs["usage_metadata"]
    return out


@dataclass
class _RunState:
    stack: ExitStack | None
    run: Any  # langsmith.RunTree
    ambient_enabled: bool = True


class LangSmithSink(ObservabilitySink):
    name = "langsmith"

    def __init__(self, settings: Any, redactor: Redactor, *, client: Any = None, **client_options: Any):
        """`client_options` are passed to `langsmith.Client` (e.g. `auto_batch_tracing=False` in tests)."""
        try:
            import langsmith as ls
            from langsmith import run_helpers, run_trees
            from langsmith import utils as ls_utils
        except ImportError as exc:  # pragma: no cover - depends on environment
            raise SinkError(self.name, "the 'langsmith' package is not installed") from exc
        self._ls, self._helpers, self._run_trees, self._ls_utils = ls, run_helpers, run_trees, ls_utils
        self._settings = settings
        self._redactor = redactor
        self._project = settings.langsmith_project
        if client is None:
            key = settings.langsmith_api_key.get_secret_value() if settings.langsmith_api_key else None
            options = {"api_key": key, "api_url": settings.langsmith_endpoint or None,
                       "hide_inputs": self.hide_inputs, "hide_outputs": self.hide_outputs, **client_options}
            client = ls.Client(**options)
        self.client = client

    # ---- masking hooks (installed on the Client; applied to every run it sends) ---------------
    def hide_inputs(self, inputs: dict) -> dict:
        try:
            is_llm = isinstance(inputs, dict) and ("messages" in inputs or "prompts" in inputs)
            allowed = self._settings.capture_messages if is_llm else self._settings.capture_inputs
            if not allowed or not inputs:
                return {}
            return self._redactor.redact(to_jsonable(inputs, self._settings.max_payload_chars))
        except Exception:  # noqa: BLE001 - never leak on failure
            return {}

    def hide_outputs(self, outputs: dict) -> dict:
        try:
            if not outputs:
                return {}
            if not self._settings.capture_outputs:
                return _usage_skeleton(outputs)  # keep token usage / model name visible, drop all content
            return self._redactor.redact(to_jsonable(outputs, self._settings.max_payload_chars))
        except Exception:  # noqa: BLE001
            return {}

    # ---- span lifecycle -----------------------------------------------------------------------
    def start_span(self, span: Span, event: ObservabilityEvent) -> None:
        ambient = self._helpers.get_current_run_tree()
        if span.run_type == RunType.LLM:
            # Deferred: decide at the end whether LangChain already traced this call natively.
            span.sink_state[_STATE_KEY] = _RunState(None, ambient or self._parent_run(span),
                                                    ambient_enabled=self._ls_utils.tracing_is_enabled() is True)
            return
        stack = ExitStack()
        try:
            if ambient is None:
                parent = self._parent_run(span)
                # Root span (or a span resumed in a context that lost the SDK context): enable tracing explicitly.
                stack.enter_context(self._ls.tracing_context(enabled=True, client=self.client,
                                                             project_name=self._project, parent=parent))
            run = stack.enter_context(self._ls.trace(
                name=span.name, run_type=_LS_RUN_TYPES[span.run_type], inputs=self._inputs(event),
                client=self.client, project_name=self._project, run_id=span.run_id,
                tags=list(span.tags) or None, metadata=self._metadata(span, event)))
        except Exception:
            stack.close()
            raise
        span.sink_state[_STATE_KEY] = _RunState(stack, run)

    def end_span(self, span: Span, event: ObservabilityEvent) -> None:
        state: _RunState | None = span.sink_state.pop(_STATE_KEY, None)
        if span.run_type == RunType.LLM:
            self._end_llm(span, event, state)
            return
        if state is None:
            return
        try:
            run = state.run
            run.add_metadata(self._end_metadata(span, event))
            error = self._error_text(event)
            run.end(outputs=self._outputs(event), error=error)
        finally:
            if state.stack is not None:
                state.stack.close()  # trace teardown: patches the run and restores the SDK context

    def _end_llm(self, span: Span, event: ObservabilityEvent, state: _RunState | None) -> None:
        if state is not None and span.framework_run_ids and state.ambient_enabled:
            return  # LangChain's tracer already created the LLM run under the current parent
        parent = state.run if state is not None else self._parent_run(span)
        md = {**self._metadata(span, event), **self._end_metadata(span, event)}
        if span.provider:
            md["ls_provider"] = span.provider
        if span.model:
            md["ls_model_name"] = span.model
        kwargs = dict(inputs=self._inputs(event, llm=True), start_time=span.start_time, extra={"metadata": md},
                      tags=list(span.tags) or None)
        if parent is not None:
            run = parent.create_child(span.name, "llm", run_id=span.run_id, **kwargs)
        else:
            run = self._run_trees.RunTree(name=span.name, run_type="llm", id=span.run_id, client=self.client,
                                          project_name=self._project or "default", **kwargs)
        if event.input_tokens is not None or event.output_tokens is not None:
            usage = {k: v for k, v in (("input_tokens", event.input_tokens), ("output_tokens", event.output_tokens),
                                       ("total_tokens", event.total_tokens)) if v is not None}
            run.set(usage_metadata=usage)
        run.end(outputs=self._outputs(event), error=self._error_text(event), end_time=event.end_time)
        run.post()

    # ---- point events -------------------------------------------------------------------------
    def emit(self, event: ObservabilityEvent, span: Span | None) -> None:
        if enum_value(event.event_type) in _LIFECYCLE or span is None:
            return
        target = next((s for s in [span, *span.ancestors()]
                       if isinstance(s.sink_state.get(_STATE_KEY), _RunState) and s.sink_state[_STATE_KEY].stack), None)
        if target is None:
            return
        run = target.sink_state[_STATE_KEY].run
        fields = {k: getattr(event, k) for k in _EVENT_FIELDS if getattr(event, k) is not None}
        run.add_event({"name": enum_value(event.event_type), "time": iso_utc(event.timestamp),
                       "kwargs": to_jsonable({**fields, **(event.attributes or {})}, 500)})
        et = event.event_type
        if et in (EventType.RETRY_STARTED, EventType.RETRY_COMPLETED):
            run.add_tags(["retry"])
        elif et == EventType.CORRELATION_LINKED and event.request_id:
            for s in [span, *span.ancestors()]:
                st = s.sink_state.get(_STATE_KEY)
                if isinstance(st, _RunState) and st.run is not None:
                    st.run.add_metadata({"request_id": event.request_id})

    def flush(self, timeout: float | None = None) -> None:
        flush = getattr(self.client, "flush", None)
        if callable(flush):
            flush()

    def shutdown(self) -> None:
        self.flush()

    # ---- helpers ------------------------------------------------------------------------------
    @staticmethod
    def _parent_run(span: Span) -> Any:
        for s in span.ancestors():
            st = s.sink_state.get(_STATE_KEY)
            if isinstance(st, _RunState) and st.stack is not None:
                return st.run
        return None

    def _metadata(self, span: Span, event: ObservabilityEvent) -> dict[str, Any]:
        md = {
            "request_id": span.request_id, "observability_trace_id": span.trace_id, "observability_run_id": span.run_id,
            "run_kind": span.run_type.value, "component": span.component, "operation": span.operation,
            "provider": span.provider, "model": span.model, "tool_name": span.tool_name, "connector": span.connector,
            "parent_llm_run_id": span.parent_llm_run_id, "retry_count": span.retry_count,
            "environment": event.environment, "service": event.service,
        }
        md.update(event.metadata or {})
        return {k: v for k, v in md.items() if v is not None}

    @staticmethod
    def _end_metadata(span: Span, event: ObservabilityEvent) -> dict[str, Any]:
        md: dict[str, Any] = {"status": event.status, "latency_ms": event.latency_ms}
        if span.request_id:
            md["request_id"] = span.request_id
        for k in ("usage_source", "estimated_cost", "cost_currency", "pricing_source", "retry_count", "error_type"):
            v = getattr(event, k)
            if v is not None:
                md[k] = v
        if event.attributes:
            md.update({f"attr.{k}": v for k, v in event.attributes.items()})
        return {k: v for k, v in md.items() if v is not None}

    @staticmethod
    def _inputs(event: ObservabilityEvent, llm: bool = False) -> dict[str, Any]:
        out: dict[str, Any] = {}
        if event.messages is not None:
            out["messages"] = event.messages
        if event.inputs is not None:
            out["inputs" if llm or not isinstance(event.inputs, dict) else "input"] = event.inputs
        if len(out) == 1 and "input" in out:
            return out["input"]
        return out

    @staticmethod
    def _outputs(event: ObservabilityEvent) -> dict[str, Any]:
        if event.outputs is None:
            return {}
        return event.outputs if isinstance(event.outputs, dict) else {"output": event.outputs}

    @staticmethod
    def _error_text(event: ObservabilityEvent) -> str | None:
        if enum_value(event.status) != Status.FAILED.value:
            return None
        return f"{event.error_type or 'Error'}: {event.error_message or ''}".strip()
